name: Deploy
 
on:
  push:
    branches: [master]
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm install
 
      - name: Build
        run: npm run docs:build 
 
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.JSTOOL_TOKEN }}
          publish_dir: docs/.vitepress/dist